### ISSUE TITLE
ERROR: get: dial tcp: lookup: read udp: read: connection refused

### ISSUE THREAD

**Issue by njzjz** [scop/pre-commit-shfmt#20]
See https://results.pre-commit.ci/run/github/114006193/1699907034.povI7ysrT0KE7N6-XDqIXA

```
shfmt....................................................................Failed
- hook id: shfmt
- exit code: 1

wrun: ERROR: get https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64#0264c424278b18e22453fe523ec01a19805ce3b8ebf18eaf3aadc1edc23f42e3: Get "https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64#0264c424278b18e22453fe523ec01a19805ce3b8ebf18eaf3aadc1edc23f42e3": dial tcp: lookup github.com on [::1]:53: read udp [::1]:42344->[::1]:53: read: connection refused
wrun: ERROR: get https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64#0264c424278b18e22453fe523ec01a19805ce3b8ebf18eaf3aadc1edc23f42e3: Get "https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64#0264c424278b18e22453fe523ec01a19805ce3b8ebf18eaf3aadc1edc23f42e3": dial tcp: lookup github.com on [::1]:53: read udp [::1]:33573->[::1]:53: read: connection refused
```

**Comment by scop** [comment]
Perhaps a DNS issue at their end, or a resolver configuration that the CGO_ENABLED=0 wrun builds does not work with.

I suggest retrying the job to see if that might help.

By the way, the new main `shfmt` hook may not be the best one to use with pre-commit.ci, not sure if wrun's caches will be included in their automated caches, and there seems to be no way to control what gets included. In that sense, the shfmt-src or shfmt-docker might yield better results. This is just an unverified hunch for now.

**Comment by djhoese** [comment]
After #19 was fixed I tried switching from `shfmt-src` to `shfmt` and I now get this connection refused error on pre-commit.ci also. I guess I'll go back to `shfmt-src`. Thanks.

**Comment by xmfcx** [comment]
We've also got the same error on:
- https://results.pre-commit.ci/run/github/41331761/1700039086.08oZDBW8SECNTV4SbnF1NA
```
shfmt....................................................................Failed
- hook id: shfmt
- exit code: 1

wrun: ERROR: get https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64#0264c424278b18e22453fe523ec01a19805ce3b8ebf18eaf3aadc1edc23f42e3: Get "https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64#0264c424278b18e22453fe523ec01a19805ce3b8ebf18eaf3aadc1edc23f42e3": dial tcp: lookup github.com on [::1]:53: read udp [::1]:35774->[::1]:53: read: connection refused
```

**Comment by scop** [comment]
New versions of this hook are using [wrun](https://github.com/scop/wrun) to download prebuilt upstream executables on the fly. [pre-commit.ci disallows network access at runtime](https://github.com/pre-commit-ci/issues/issues/196#issuecomment-1810937079), so as long as this is the case, this approach does not work with it. The `-src` and `-docker` versions do AFAIK work there, as they require networking in a different phase of the setup.

I'm considering other approaches for the download, not quite sure about the way I'll go, but leaving open for now for visibility.

**Comment by scop** [comment]
v3.7.0-4 switches to setuptools-download, that should make pre-commit.ci happier.
